from typing import Set, Tuple, List, Dict, Union, Optional
from io import TextIOWrapper

IndexRange = Union[int, Tuple[int, Optional[int]]]

class Translator:
    def __init__(self, associations: Dict[str, str]): ...
    def translate(self, text: str) -> str: ...

class Structure:
    def __init__(self, transcriber: "Transcriber", lang: "Language", start: int) -> None: ...
    @property
    def transcriber(self) -> "Transcriber": ...
    def translate_index(self, i: int) -> int: ...
    def get_index(self, index_range: IndexRange, end: Optional[int] = None) -> str: ...

class Language:
    translator: Translator
    def __init__(self, prefix: str, name: str, filename: str, translation: Optional[Translator] = None) -> None: ...
    @property
    def transcriptions(self): ...
    @transcriptions.setter
    def transcriptions(self, value: Set["Transcription"]): ...
    @property
    def prefix(self) -> str: ...
    @prefix.setter
    def prefix(self, value: str) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def filename(self) -> str: ...
    @filename.setter
    def filename(self, value: str) -> None: ...
    @property
    def frozen(self) -> bool: ...
    @frozen.setter
    def frozen(self, value: bool) -> None: ...
    def translate(self, text: str) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other): ...

class Transcription:
    def __init__(self, index: IndexRange, transcriber: "Transcriber"): ...
    @staticmethod
    def _lang_key(lang: Language) -> str: ...
    def load(self, lang: Language, lines: List[str]) -> None: ...
    def evict_lang(self, lang_key: str) -> None: ...
    @property
    def loaded_for(self) -> Set[str]: ...
    @property
    def index_range(self) -> IndexRange: ...
    @property
    def text(self) -> str: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other) -> bool: ...

class Cache:
    transcriber: "Transcriber"
    transcriptions: Dict[IndexRange, Transcription]
    lines: List[str]
    def __init__(self, transcriber: "Transcriber") -> None: ...
    def reset_all(self) -> None: ...
    def reset(self) -> None: ...
    def get_index(self, index_range: IndexRange) -> str: ...
    def read(self, file: TextIOWrapper) -> None: ...

class Transcriber:
    basepath: str
    extension: str
    def __init__(self, basepath: str, extension: str, lang: Language) -> None: ...
    @property
    def path(self) -> str: ...
    @property
    def lang(self) -> Language: ...
    @lang.setter
    def lang(self, value: Language) -> None: ...
    def reset(self) -> None: ...
    def set_lang(self, lang: Language) -> None: ...
    def load(self, encoding: str = "utf-8") -> None: ...
    def get_index(self, index_range: IndexRange, end: Optional[int] = None) -> str: ...